# ${ZDOTDIR}/.zprofile
# >>>>>>>> [update 2026-01-17] >>>>>>>>

# =========================================
# >>> 全局 PATH
# =========================================
typeset -U path # PATH去重,放在 path()之前

user_paths=(
    "/opt/homebrew/bin"
    "/opt/homebrew/sbin"
    "${HOME}/.local/bin"

)
dev_paths=(
    "${PIPX_BIN_DIR}"
    "${PNPM_HOME}"
    "${PNPM_HOME}/bin"
    "${FNM_PATH}"
    "${CARGO_HOME}/bin"
    "${BUN_INSTALL}/bin"
    "${HOME}/.dotnet/tools"
    "${XDG_CONFIG_HOME}/lmstudio/bin"
)
sys_paths=(
    "/usr/local/bin"
    "/usr/bin"
    "/bin"
    "/usr/sbin"
    "/sbin"
    "/System/Cryptexes/App/usr/bin"
    "/Library/Apple/usr/bin"
    "/Library/Frameworks/Mono.framework/Versions/Current/Commands"
)
path=(
    $user_paths
    $dev_paths
    $sys_paths
)
export PATH="${(j.:.)path}"  #必要分隔(path 正确时没有明显差别)

# =========================================
# >>> Conda
# =========================================
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/felix/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/felix/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/felix/miniconda3/etc/profile.d/conda.sh"
    else
        # 检查PATH中是否已包含conda路径，避免重复添加
        if [[ ! "$PATH" =~ "/Users/felix/miniconda3/bin" ]]; then
            export PATH="/Users/felix/miniconda3/bin:$PATH"
        fi
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# conda 命令存在(conda已安装)则 激活 env
if command -v conda >/dev/null 2>&1; then
	conda activate dev
    echo '[c6x] 已激活 conda: dev'
fi

# <<<<<<<< .zprofile END <<<<<<<<
