# ${ZDOTDIR}/.zshrc
# >>>>>>>> [update: 2026-01-17] >>>>>>>>

# >>> 顶部交互 guard <<<
if [[ $- != *i* ]]; then
    return
fi
# XDG fallback保护
: "${XDG_CONFIG_HOME:=$HOME/.config}"
: "${XDG_CACHE_HOME:=$HOME/.cache}"
: "${XDG_DATA_HOME:=$HOME/.local/share}"
: "${XDG_STATE_HOME:=$HOME/.local/state}"

# 终端编辑方式
# -e: emac | -v: vim
bindkey -e

# =========================================
# >>> 🌈 Zinit 终端zsh主题
# =========================================

# >>> Zinit INSTALLATION (官方方案) <<<
ZINIT_HOME="${XDG_DATA_HOME}/zinit/zinit.git"
# 核对 zinit 父目录的存在
if [[ ! -d "${ZINIT_HOME}" ]]; then
    mkdir -p "$(dirname "${ZINIT_HOME}")" #dirname 表示文件父目录存在
fi
# 首次加载拉取仓库 (若不存在则拉取仓库并创建)
if [[ ! -d "${ZINIT_HOME}/.git" ]]; then
    git clone https://github.com/zdharma-continuum/zinit.git "${ZINIT_HOME}"
fi
# 始终加载zinit
source "${ZINIT_HOME}/zinit.zsh"

# cache用于加速补全
ZSH_CACHE="${XDG_CACHE_HOME}/zsh/zcompcache"
if [[ ! -d "${ZSH_CACHE}" ]]; then
    mkdir -p "${ZSH_CACHE}"
fi

zstyle ':completion:*' cache-path "${ZSH_CACHE}"   #补全缓存
zstyle ':completion:*' menu select                 #补全便捷菜单
zstyle ':compinstall' filename "${ZDOTDIR}/.zshrc" #初始化补全系统,推荐定位到.zshrc

# =========================================
# >>> fpath
# fpath 是zsh专用,放在.zshrc(PATH放在.zprofile)
# fpath 要放在 compinit 之前, 执行函数放在 compinit 之后
# =========================================
# 创建 zfunc目录来存放未来的补全工具(备用)
if [[ -d "${XDG_DATA_HOME}/zfunc" ]]; then
    fpath+=("${XDG_DATA_HOME}/zfunc")
fi
# homebrew 自动补全, 将homebrew的zsh/site-functions加入fpath(官方步骤)
if command -v brew >/dev/null 2>&1; then
    eval "$(brew shellenv)"
else
    echo "[zshrc警告] 找不到 brew/homebrew"
fi

# =========================================
# >>> 初始化 compinit 自动补全
# =========================================
autoload -Uz compinit
compinit

# zinit 插件放在compint之后
zinit ice pick'async.zsh' src'pure.zsh' # ice 在 light 之前
zinit light sindresorhus/pure
zinit light zsh-users/zsh-syntax-highlighting
zinit light hlissner/zsh-autopair

# =========================================
# >>> 自动补全插件
# =========================================

# >>> uv completions
if command -v uv >/dev/null 2>&1; then
    eval "$(uv generate-shell-completion zsh)"
else
    echo "[zshrc警告] 找不到 uv"
fi

# >>> ty completions
if command -v ty >/dev/null 2>&1; then
    eval "$(ty generate-shell-completion zsh)"
else
    echo "[zshrc警告] 找不到 ty"
fi

# >>> comfy-cli completion
if command -v comfy >/dev/null 2>&1; then
    eval "$(comfy --show-completion zsh)"
else
    echo "[zshrc警告] 找不到 comfy-cli"
fi

# >>> bun completions
if [[ -s "${BUN_INSTALL}/_bun" ]]; then
    source "${BUN_INSTALL}/_bun"
else
    echo "[zshrc警告] 找不到 _bun"
fi

# >>> homebrew completions

# =========================================
# >>> Shell hook
# =========================================
# direnv shell hook (弃用)
# if command -v direnv >/dev/null 2>&1; then
# 	eval "$(direnv hook zsh)"
# else
# 	echo "[zshrc警告] 找不到 direnv"
# fi

# =========================================
# >>> Python
# =========================================
uv_pip() {
    uv run python -m pip "$@"
}

uv_index() {
    echo "[c6x] uv run python -m pip index versions ..."
    uv run python -m pip index versions "$@"
}

uv_install() {
    echo "[c6x] uv run python -m pip install ..."
    uv run python -m pip install "$@"
}

alias flake7="flake8 --ignore E265,E231,E302,E251,F403,F405"
flake+() {
    autoflake "$@"
    autoflake --remove-all-unused-imports -i "$@"
    isort "$@"
}

# =========================================
# >>> Node.js
# =========================================
# [fnm 初始化]
# 自动处理各目录 PATH 优先级)
if command -v fnm >/dev/null 2>&1; then
    eval "$(fnm env --use-on-cd --shell zsh)"
fi

# =========================================
# >>> 🚀 Alias 与 快捷func
# =========================================

alias xmind="open -a /Applications/Xmind.app"
alias toys="open -a /Applications/DevToys.app"
alias wetool="open -a /Applications/wechatwebdevtools.app"
alias chat="open -a chatgpt"
alias flutterflow="open -a flutterflow"
alias c2p="code2prompt" #代码转提示词

alias pdm="podman"                              #podman-cli
alias pdm_app="open -a Podman\ Desktop.app"     #podman-desktop
alias mynotes="cd ${MYNOTES}"                   #我的笔记git仓库
alias zettlr="open -a /Applications/Zettlr.app" # zettlr的markdown编辑器

# >>>>>>>>>> 💟 Git 类
alias ghc="gh copilot"

# ▶️ git提交记录
git_add() {
    echo "[c6x] git add ."
    git add .
    echo "[c6x] 提交批注: git commit -m <path>"
    git commit -m "$1"
    echo "✅ Done! 提交完成, 发布命令: git push"
    echo "⚠️ 检查私人信息: prep_key <path>"
}

# >>>>>>>>>> 💟 系统类
alias ll="lla -T --sort-dirs-first"
alias rp="runpodctl"
alias rclone_web="rclone rcd --rc-web-gui"
alias copy="rsync -ah --info=progress2"
alias croc_send="croc send --hash imohash --code coffelix"
alias mactop="sudo mactop"

# 按顺序列出PATH
echo_path() {
    echo "按顺序列出 PATH"
    echo $PATH | tr ':' '\n' | nl -ba
}
echo_fpath() {
    echo "按顺序列出 fpath"
    echo $FPATH | tr ':' '\n' | nl -ba
}

# ▶️ 扫描目录中的md文件是否包含敏感信息(screte/api-key/...)
grep_key() {
    grep -rnE "(api[_-]?key|secret|password|token|sk-|pk-|AKIA)" \
        --include="*.md" \
        "$@"
}

# ▶️ 快捷find -print/-delete
fd_prt() {
    find . -maxdepth "$1" -name "$2" -print
}
fd_del() {
    find . -maxdepth "$1" -name "$2" -delete
}

# ▶️ ssh remote
alias ssh_fedora="ssh felix@192.168.0.121"
ssh_nas() {
    echo "进入BlueSpaceNas"
    ssh sshd@192.168.0.101
}

# ▶️ homebrew
alias brew_s="brew search"
brew_up() {
    echo "进行每日检查..."
    brew outdated
    echo "🤗过期包检查完毕, 准备更新brew主程序..."
    brew update
    echo "🤗 brew主程序更新完毕, 准备更新包和依赖..."
    brew upgrade
    echo "🤗 brew包依赖更新完毕, 准备清理..."
    brew cleanup
    brew autoremove
    echo "🔰 brew清理完毕, 准备健康检测..."
    brew doctor
    echo "准备清理缓存 (pnpm | npm)..."
    pnpm store prune
    npm cache verify
    echo "🔰 今日检查完毕, Have Fun Everyday~"
}

# ▶️ conda
conda_clean() {
    echo "正在执行 conda doctor..."
    conda doctor
    echo "正在执行 conda clean..."
    conda clean --all -y
    echo "Conda已清洁!"
}

# ▶️ 网络测试
x_curl() {
    echo "当前IP所在地区查询中:"
    echo "😺 ifconfig.co..."
    curl ifconfig.co/country
    echo "😺 ip-api.com.co..."
    curl -s http://ip-api.com/json | jq '.country'
    echo "😺 ipinfo.io..."
    curl "https://api.ipinfo.io/lite/me?token=d1ce7d0f23ff7e"
}
x_ping() {
    echo "curl ipinfo.io/country -->"
    curl ipinfo.io/country
    echo "speedtesting... -->"
    speedtest -L
    speedtest --progress-update-interval 1000
    echo "网络测试结束, 运行 'curl ipfinfo.io/json' 获取更多信息"
}
x_pingweb() {
    echo '正在打开测试页面(speed.cloudflare.com)...'
    open https://speed.cloudflare.com/
}

# >>>>>>>>>> 💟 工具类
# ▶️ translate-shell
alias t_p="trans -speak"
alias t_d="trans -d"
alias t_b="trans -b"
alias t_cn="trans zh-CN:en -b"

# ▶️ vpn
lets() {
    echo "启动LetsVPN"
    open -a "letsvpn" --background
}
# ▶️ 代理(mac暂时不用)
mihomo() {
    echo "启动 Clash Party(Mihomo Party)"
    open -a "Clash Party.app"
}

# >>>>>>>>>> 💟 开发工具类
# ▶️ zed
x_zed() {
    echo "启动 zed"
    zed "/Users/felix/ComfyUI/custom_nodes/cfx_nodes/user/editor_workspace/"
}
zednote() {
    echo "启动 zed 编辑 c6x-mynotes 笔记"
    zed "${MYNOTES}"
}
zednodes() {
    echo "启动 zed 编辑 ComfyUI - cfx_nodes"
    source ${CF_LOCAL}/.venv/bin/activate
    zed "${MYNODES}"
}

# ▶️ vscode
x_code() {
    echo "启动 vscode"
    code "${MYNODES}/user/editor_workspace/"
}

# ▶️ Dyad
x_dyad() {
    echo "启动Dyad构建"
    if [[ ! "$PWD" == /Users/felix/dyad-apps/* ]]; then
        echo 切换至Dyad工作路径...
        cd ${MAC_4T}/Codev/Dyad/
    fi
    open -a "dyad"
}

# ▶️ Figma
figma() {
    echo "启动Figma, 检查环境目录..."
    if [[ ! "$PWD" == ${MAC_4T}/Creative/Figma* ]]; then
        echo 切换至Figma工作路径...
        cd ${MAC_4T}/Creative/Figma/
    fi
    open -a "figma"
}

# >>>>>>>>>> 💟 应用程序类
# ▶️ Blender
alias bl="blender"
blx() {
    echo "启动 blender 最新版本"
    open -a "/Applications/Blender.app/Contents/MacOS/Blender"

}

# ▶️ NukeX13.1v1
nuke() {
    echo "启动 NukeX13.1v1"
    open -a "NukeX13.1v1.app"
}

# ▶️ Facefusion
facefusion() {
    echo "启动Facefusion"
    cd ${FACEFUSION_HOME}

    echo "进入facefusion 虚拟环境, 退出记得切换"
    source ${FACEFUSION_HOME}/.venv/bin/activate

    echo "正在更新仓库..."
    git pull
    echo "仓库更新完成!"

    echo "正在更新依赖..."
    uv run python -m pip install -r requirements.txt
    echo "依赖更新完成!"

    echo '正在访问 http://127.0.0.1:7860)...'
    echo "[c6x] 运行: uv run facefusion.py run --open"
    GRADIO_SERVER_NAME="0.0.0.0" \
        python facefusion.py run --open
}

# ▶️ Krita
krita() {
    echo "启动 Krita"
    open -a "/Applications/krita.app"
}

# ▶️ Aseprite
x_aseprite() {
    echo "启动 aseprite"
    if [[ ! "$PWD" == ${MAC_4T}/Creative/PixelArt/Aseprite-Works* ]]; then
        echo 切换至Aseprite工作路径...
        cd ${MAC_4T}/Creative/PixelArt/Aseprite-Works
    fi
    open -a "Aseprite"
}

# Pixelorama
pixelorama() {
    echo "启动Pixelorama"
    if [[ ! "$PWD" == ${MAC_4T}/Creative/PixelArt/Pixelorama-Works* ]]; then
        echo 切换至Pixelorama工作路径...
        cd ${MAC_4T}/Creative/PixelArt/Pixelorama-Works/
    fi
    open -a "Pixelorama"
}

# >>>>>>>>>> 💟 游戏引擎类
# ▶️ Godot
x_godot() {
    echo "启动Godot最新版"
    if [[ ! "$PWD" == ${GODOT_HOME}/* ]]; then
        echo "切换至Godot工作路径..."
        cd ${GODOT_HOME}
    fi
    open -a "/Applications/Godot.app/Contents/MacOS/Godot"
}

# ▶️ Phaser
phaser() {
    echo "启动 PhaserJS"
    open -a "Phaser Launcher" && cd ${MAC_4T}/Gamedev/_OTE/PhaserJS
}

# ▶️ Defold
defold() {
    echo "启动 Defold"
    open -a defold
}

# ▶️ Renpy
renpy() {
    echo "启动 Renpy视觉小说"
    open -a "/Applications/renpy-8.4.0-sdk/renpy.app"
}

# ▶️ RPG-Maker-MZ 的快捷函数
rpg() {
    echo "启动 RPG Maker MZ"
    if [[ ! "$PWD" == ${RPG_HOME}/* ]]; then
        echo "切换至RMMZ工作路径..."
        cd ${RPG_HOME}
    fi
    open -a "/Users/felix/Library/Application Support/Steam/steamapps/common/RPG Maker MZ/RPGMZ.app"
}

# <<<<<<<< .zshrc END <<<<<<<<
